// import './globals.css'
import { Inter } from 'next/font/google'
import './css/index.css'
import 'bootstrap/dist/css/bootstrap.min.css';

// import '/node_modules/font-awesome/css/font-awesome.min.css'; 

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Second Brain',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </head>
      <body>{children}</body>
    </html>
  )
}
