// import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import './css/index.css'
// import '/node_modules/font-awesome/css/font-awesome.min.css'; 

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Second Brain',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
